version: '3.1'
services:
  server:
    image: dada971/shop-crm-server
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    network_mode: 'host'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE handle error silently
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - 3306:3306
