local:
    hosts:
        local_web_server_1:
            ansible_host: 192.168.33.10
#            ansible_ssh_private_key_file: '/home/dada/VMs/Ansible_docker_terraform/.vagrant/machines/host0/virtualbox/private_key'
#prod:
#    hosts:
#        web:
#            #ansible_host: localhost
