version: '3.1'
services:
  server:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 80:8080
    networks:
      - lan0

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
      MYSQL_DATABASE: shopcrm
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    networks:
      - lan0

networks:
  lan0:
    driver: bridge