spring:
  datasource:
    username: spring
    password: spring
    url: jdbc:mysql://localhost:3309/shopcrm
    driver-class: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
      port: 5555
    restart:
      enabled: true
      poll-interval: 5s
      quiet-period: 1s
  thymeleaf:
    enable-spring-el-compiler: true
server:
  error:
    whitelabel:
      enabled: false
    path: /error